backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produits"
    label: "Produits"
    folder: "admin/data/produits"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string", required: true }
      - { label: "Nom", name: "name", widget: "string", required: true }
      - { label: "Prix", name: "price", widget: "number", value_type: "int", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Cat√©gorie", name: "category", widget: "select", options: ["corporel", "chambre", "thiouraye", "vetement"], required: true }
